module.exports = [
  {
    name: 'Pink and blue Bodysuit',
    serialId: 1,
    description:
      "Here, we begin a comeback tour where we seemingly last left off: With not only the first album under Taylor's new record contract that she owns but that also had its live iteration cancelled. The candy coated colours of this Versace bodysuit are an on-brand callout to the Lover aesthetic while also being very signature to the iridescent embellishments that Versace is known for. This is what you call perfect brand alignment - what a great designer to bring this vision to life. @taylorswiftstyled",
    category: 'Lover',
    designer: 'Versace',
    pointValue: 3,
    image: '/static/outfits/1.webp',
  },
  {
    name: 'Blue and gold Bodysuit',
    serialId: 2,

    category: 'Lover',
    designer: 'Versace',
    pointValue: 3,
    image: '/static/outfits/2.jpeg',
  },
  {
    name: 'Purple with tassels Bodysuit',
    serialId: 3,
    description:
      'I truly love the colours and the new ombré boots with this bodysuit - the exaggerated fringe-y tassels a little less so. But these Versace bodysuits are truly a work of art. @taylorswiftstyled',
    category: 'Lover',
    designer: 'Versace',
    pointValue: 3,
    image: '/static/outfits/3.jpeg',
  },
  {
    name: 'Black The Man Jacket',
    serialId: 4,

    category: 'Lover',
    designer: 'Versace',
    pointValue: 2,
    image: '/static/outfits/4.jpeg',
  },
  {
    name: 'Silver The Man Jacket',
    serialId: 5,
    description:
      'Between the two sequinned blazer moments Taylor opts for when singing "The Man", my preference is actually for V2 at the moment. The pinstripes allude to classic business attire but the sparkles make it perfect for stage. The interplay between her ombré Louboutins also nicely tie in to the gold hardware on her jacket. @taylorswiftstyled',
    category: 'Lover',
    designer: 'Versace',
    pointValue: 2,
    image: '/static/outfits/5.webp',
  },
  {
    name: 'Blue Guitar',
    serialId: 6,
    description:
      "During her Lover set, she has a baby pink and a baby blue option and during her Fearless set, a custom sparkly version ✨With that, it warms my heart to see a callback to one of Taylor's previously most famed guitars from the Fearless era. Back then, the original sparkly guitar was a Taylor Guitars Grand Symphony that also had Swarovski crystals hand glued to it. As we know from behind the scenes tour footage, this Gibson was also hand-customized by talented, highly specialized musical artisans. ;) @taylorswiftstyled",
    category: 'Lover',
    designer: 'Gibson Guitar',
    pointValue: 2,
    image: '/static/outfits/6.webp',
  },
  {
    name: 'Pink Guitar',
    serialId: 7,
    description:
      "During her Lover set, she has a baby pink and a baby blue option and during her Fearless set, a custom sparkly version ✨With that, it warms my heart to see a callback to one of Taylor's previously most famed guitars from the Fearless era. Back then, the original sparkly guitar was a Taylor Guitars Grand Symphony that also had Swarovski crystals hand glued to it. As we know from behind the scenes tour footage, this Gibson was also hand-customized by talented, highly specialized musical artisans. ;) @taylorswiftstyled",
    category: 'Lover',
    designer: 'Gibson Guitar',
    pointValue: 2,
    image: '/static/outfits/7.jpeg',
  },
  {
    name: 'Fringe dress',
    serialId: 8,
    description:
      "This is Taylor Swift at her most classic for the stage - a fringed, sparkly dress and boots. It doesn't get more staple than that. And I may or may not be emotional thinking about the longstanding history Taylor has forging iconic tour looks with this designer. You may recall the iconic opening look of the Speak Now Tour - also a gold fringe dress - was RC. A journey through the eras, indeed. 💛 @taylorswiftstyled",
    category: 'Fearless',
    designer: 'Roberto Cavalli',
    pointValue: 3,
    image: '/static/outfits/8.jpeg',
  },
  {
    name: 'Tentacle dress',
    serialId: 9,
    description:
      'This dress was incredibly fun in motion - the degradé here is thanks to thousands of hand-applied Swarovski crystals. @taylorswiftstyled',
    category: 'Fearless',
    designer: 'Roberto Cavalli',
    pointValue: 3,
    image: '/static/outfits/9.jpeg',
  },
  {
    name: 'Noodle dress',
    serialId: 10,
    category: 'Fearless',
    designer: 'Roberto Cavalli',
    pointValue: 3,
    image: '/static/outfits/10.jpeg',
  },
  {
    name: 'Orange flower dress',
    serialId: 11,
    description:
      "It's of zero surprise to me that this ruffled, tie-front dress that Taylor wears for the evermore section on tour is by Etro. You'll recall me specifically name checking them as a point of reference for the designs of her folkmore sections as part of my TSS Predictions post. The Grammy performance really was a key jumping off point to nailing the bohemian goddess cottagecore look worthy of these albums visuals. @taylorswiftstyled",
    category: 'Evermore',
    designer: 'Etro',
    pointValue: 2,
    image: '/static/outfits/11.jpeg',
  },
  {
    name: 'Bronze dress',
    serialId: 12,
    description:
      'I love that this burgundy fil coupé dress has ruffled tiers that still speak to the original version of the dress while still having its own original elements like a flowier empire waist. This version feels more appropriate to some of the witch-like woodsy elements of Evermore (and, dare I say, a tinsel-like vibe that feels seasonally appropriate to "tis the damn season"?) perhaps better than the original version which leans more street style-friendly in comparison to her other costuming. @taylorswiftstyled',
    category: 'Evermore',
    designer: 'Etro',
    pointValue: 4,
    image: '/static/outfits/11.jpeg',
  },
  {
    name: 'Pink Gown',
    serialId: 13,
    description:
      'The starburst bodice design feels just the right amount of ethereal and "sparkling" for a song like "Enchanted" @taylorswiftstyled',
    category: 'Speak Now',
    designer: 'Zuhair Murad',
    pointValue: 5,
    image: '/static/outfits/13.jpeg',
  },
  {
    name: 'Champagne Gown',
    serialId: 14,
    description:
      "This stunning ballgown is an architectural feat and gives us a very strong throwback to Taylor's Valentino ballgown on the Speak Now Tour. @taylorswiftstyled",
    category: 'Speak Now',
    designer: 'Nicole + Felicia',
    pointValue: 5,
    image: '/static/outfits/14.jpeg',
  },
  {
    name: 'Tissue Gown',
    serialId: 15,
    description:
      'This gown is a big shift from the larger ballgowns she’s worn previously for “Enchanted” - a little more fitted through the waist and bottom. That scooped bateau neck also reminds me of another recent near-off shoulder moment we’ve seen. @taylorswiftstyled',
    category: 'Speak Now',
    designer: 'Elie Saab',
    pointValue: 5,
    image: '/static/outfits/15.jpeg',
  },
  {
    name: 'Silver Gown',
    serialId: 16,
    description:
      "In terms of silhouette and graduating 'starburst' quality of appliqués from the torso this squared off neck and embellished design reminds me most of the V2 Zuhair Murad gown - but made much lighter and frothier and more similar to the original Speak Now Tour Valentino gown thanks to layers and layers of fluffy, ethereal tulle. @taylorswiftstyled",
    category: 'Speak Now',
    designer: 'Elie Saab',
    pointValue: 5,
    image: '/static/outfits/16.jpeg',
  },
  {
    name: 'WANEGBT',
    serialId: 17,
    description: 'We are never getting back together like ever',
    category: 'Red',
    designer: 'Ashish',
    pointValue: 3,
    image: '/static/outfits/17.jpeg',
  },
  {
    name: `Who's TS Anyway?`,
    serialId: 18,
    description: `Who's Taylor Swift Anyway? EW`,
    category: 'Red',
    designer: 'Ashish',
    pointValue: 3,
    image: '/static/outfits/18.jpeg',
  },
  {
    name: 'A Lot Going On',
    serialId: 19,
    description: 'A Lot Going On At The Moment',
    category: 'Red',
    designer: 'Ashish',
    pointValue: 3,
    image: '/static/outfits/19.jpeg',
  },
  {
    name: 'Red Guitar',
    serialId: 20,
    description:
      'Over the course of Taylor’s three hour set, she takes the time to incorporate multiple acoustic moments. Taylor previously played the standard off-the-shelf cherry version of this guitar during the NYC premiere of the “All Too Well” short film. Here, she plays it in a more on-brand maroon finish. @tylorswiftstyled',
    category: 'Red',
    designer: 'Gibson Guitar',
    pointValue: 3,
    image: '/static/outfits/20.webp',
  },
  {
    name: 'Purple Dress',
    serialId: 21,
    description:
      'This mauve-toned, chiffon gown mixes bohemian elements thanks to its ruffles and flutter sleeves and lace with very subtle stage-worthy embellishments. @taylorswiftstyled',
    category: 'Folklore',
    designer: 'Alberta Ferretti',
    pointValue: 4,
    image: '/static/outfits/21.jpeg',
  },
  {
    name: 'White Dress',
    serialId: 22,
    description:
      'Well we are certainly in for quite a ride with this tour if Taylor plans to continue to serve fresh versions of her looks. On Night 2 of Glendale, AZ Taylor switched up her goddess gown for her folklore set to this tiered, cream gown. The split sleeve details feel almost capelike, which I love. the flutter cap sleeve also feels simultaneously dainty and armour-like. @taylorswiftstyled',
    category: 'Folklore',
    designer: 'Alberta Ferretti',
    pointValue: 4,
    image: '/static/outfits/22.jpeg',
  },
  {
    name: 'Pink Dress',
    serialId: 23,
    description:
      'Splitting the difference between her two previous Alberta Ferretti dresses, this chantilly lace confection combines the saturated mauve from the purple dress with the split sleeve cape-like detail of the white dress into this dusty rose chiffon gown for Las Vegas 1. The lace detailing here feels antique and old world in the best way while the light fabric feels just ethereal and lovely - so fitting of folklore. @taylorswiftstyled',
    category: 'Folklore',
    designer: 'Alberta Ferretti',
    pointValue: 4,
    image: '/static/outfits/23.jpeg',
  },
  {
    name: 'Green Dress',
    serialId: 24,
    description:
      'I don’t think I have to expand to anyone which folklore dress is my favourite now. Taylor wears a (say it with me now) 💚 greeeeeeeeeeeeeeeeen 💚 version of this SS23 Alberta Ferretti moment. And it is glorious and wood nymph fairy goddess-worthy of a folklore set. I really enjoy the addition of the cape so that it slideshows more neatly with the other folklore gowns. @taylorswiftstyled',
    category: 'Folklore',
    designer: 'Alberta Ferretti',
    pointValue: 4,
    image: '/static/outfits/24.jpeg',
  },
  {
    name: 'Green 2 Piece',
    serialId: 25,
    description:
      "If you follow the TSSQ blog then you know I have an ongoing tag dedicated to me live reacting to Taylor in green. Needless to say that tag was popping off yesterday when Taylor swapped out her original pink co-ord set for the 1989 section of her setlist for this gree(eeeeeeeeeeee)n one. And matching booties, natch. 💚 I don't think I need to elaborate further that this set is my clear favourite between the two. Doesn't she just look like the happiest string bean in green? @taylorswiftstyled",
    category: '1989',
    designer: 'Roberto Cavalli',
    pointValue: 3,
    image: '/static/outfits/25.jpeg',
  },
  {
    name: 'Orange 2 Piece',
    serialId: 26,
    description:
      'Not only do we all get to benefit from Taylor in orange, but it’s also incredibly charming she chose to debut this colour in Florida - a state known for the fruit. @taylorswiftstyled',
    category: '1989',
    designer: 'Roberto Cavalli',
    pointValue: 3,
    image: '/static/outfits/26.jpeg',
  },
  {
    name: 'Pink 2 Piece',
    serialId: 27,
    description:
      "Another moment where a throwback to previous style was going to be an easy win. There's nothing like a matching crop top and skirt with sparkle booties to evoke the 1989 Tour. Fausto Puglisi did an incredible job with the unique diamond-shaped Swarovski work here. @taylorswiftstyled",
    category: '1989',
    designer: 'Roberto Cavalli',
    pointValue: 3,
    image: '/static/outfits/27.webp',
  },
  {
    name: 'Pink Surprise',
    serialId: 28,
    description:
      "The wonderful Jessica Jones was Taylor's main costumer for both the 1989 and reputation Tours. I had noted that this was the one outfit of her entire tour wardrobe that stood out the most to me as unlike the others - and now we know why. It's a joy to see her credited again as part of Taylor's tour. @taylorswiftstyled",
    category: 'Surprise Songs',
    designer: 'Jessica Jones',
    pointValue: 3,
    image: '/static/outfits/28.jpeg',
  },
  {
    name: 'Green Surprise',
    serialId: 29,
    description:
      "The wonderful Jessica Jones was Taylor's main costumer for both the 1989 and reputation Tours. I had noted that this was the one outfit of her entire tour wardrobe that stood out the most to me as unlike the others - and now we know why. It's a joy to see her credited again as part of Taylor's tour. @taylorswiftstyled",
    category: 'Surprise Songs',
    designer: 'Jessica Jones',
    pointValue: 3,
    image: '/static/outfits/29.jpeg',
  },
  {
    name: 'Yellow Surprise',
    serialId: 30,
    description:
      "The wonderful Jessica Jones was Taylor's main costumer for both the 1989 and reputation Tours. I had noted that this was the one outfit of her entire tour wardrobe that stood out the most to me as unlike the others - and now we know why. It's a joy to see her credited again as part of Taylor's tour. @taylorswiftstyled",
    category: 'Surprise Songs',
    designer: 'Jessica Jones',
    pointValue: 3,
    image: '/static/outfits/30.webp',
  },
  {
    name: 'Light Blue T-Shirt',
    serialId: 31,
    category: 'Midnights',
    designer: 'Oscar de la Renta',
    pointValue: 6,
    image: '/static/outfits/31.jpeg',
  },
  {
    name: 'Pink T-Shirt',
    serialId: 32,
    category: 'Midnights',
    designer: 'Oscar de la Renta',
    pointValue: 6,
    image: '/static/outfits/32.jpeg',
  },
  {
    name: 'Purple T-Shirt',
    serialId: 33,
    category: 'Midnights',
    designer: 'Oscar de la Renta',
    pointValue: 6,
    image: '/static/outfits/33.jpeg',
  },
  {
    name: 'Silver sequin T-Shirt',
    serialId: 34,
    category: 'Midnights',
    designer: 'Oscar de la Renta',
    pointValue: 6,
    image: '/static/outfits/34.jpeg',
  },
  {
    name: 'Blurple T-Shirt',
    serialId: 35,
    description: 'The elusive exclusive super confusing blue/purple/pink combo',
    category: 'Midnights',
    designer: 'Oscar de la Renta',
    pointValue: 6,
    image: '/static/outfits/35.jpeg',
  },
  {
    name: 'Navy Bodysuit',
    serialId: 36,
    description:
      'The fringe on this midnight blue bodysuit drips beautifully over her hips here and plays multiple roles. Serving to mimic raindrops for "Midnight Rain", a fun twirly moment worthy of strutting and spinning during "Bejeweled", and to add a sensual tasseled burlesque feel during that aforementioned chair dance of "Vigilante Shit". Plus it also feels kind of cheeky western glam. @taylorswiftstyled',
    category: 'Midnights',
    designer: 'Oscar de la Renta',
    pointValue: 2,
    image: '/static/outfits/36.jpeg',
  },
  {
    name: 'Blurple Scallop Bodysuit',
    serialId: 37,
    description:
      'Swapping out her other glittery bodysuit, Taylor must have been under the Vegas influence when it came to certain accessories last night. This take on the Midnights bodysuit has a lot of similarities - same colour family, spangly embellishments, and richly beaded fringe. @taylorswiftstyled',
    category: 'Midnights',
    designer: 'Zuhair Murad',
    pointValue: 2,
    image: '/static/outfits/37.jpeg',
  },
  {
    name: 'Light Pink Karma Jacket',
    serialId: 38,
    category: 'Midnights',
    designer: 'Oscar de la Renta',
    pointValue: 3,
    image: '/static/outfits/38.jpeg',
  },
  {
    name: 'Multicolor Karma Jacket',
    serialId: 39,
    category: 'Midnights',
    designer: 'Oscar de la Renta',
    pointValue: 3,
    image: '/static/outfits/39.jpeg',
  },
  {
    name: 'Magenta Karma Jacket',
    serialId: 40,
    category: 'Midnights',
    designer: 'Oscar de la Renta',
    pointValue: 3,
    image: '/static/outfits/40.jpeg',
  },
  {
    name: 'Purple Layer Gown',
    serialId: 41,
    description: 'New Dress KC N1. More details to come',
    category: 'Speak Now',
    designer: 'TBD',
    pointValue: 5,
    image: '/static/outfits/41.jpeg',
  },
  {
    _id: '64a8e5a5f7ff922658b16627',
    name: 'Orchid T-shirt',
    serialId: 42,
    description: 'New Outfit KC N1',
    category: 'Midnights',
    designer: 'Oscar de la Renta',
    pointValue: 6,
    image: '/static/outfits/42.jpeg',
  },
  {
    _id: '64b22b4ba424d098bab72deb',
    name: 'Blue Karma Jacket',
    serialId: 43,
    description: 'New Outfit Denver 1',
    category: 'Midnights',
    designer: 'Oscar de la Renta',
    pointValue: 4,
    image: '/static/outfits/43.jpeg',
  },
  {
    _id: '64d3fb1f5257dc549b04cc28',
    name: 'Purple The Man Jacket',
    description: 'New Outfit LA N5',
    category: 'Lover',
    designer: 'Versace',
    pointValue: 3,
    image: 'https://pbs.twimg.com/media/F3DwWVjWMAAPhmT?format=jpg&name=large',
  },
  {
    _id: '64d3fc735257dc549b04cc29',
    serialId: 45,
    name: 'Blue Cutout Bodysuit',
    description: 'New Outfit LA N5',
    category: 'Midnights',
    designer: 'Oscar de la Renta',
    pointValue: 3,
    image: 'https://pbs.twimg.com/media/F3EaWm6XgAE_467?format=jpg&name=large',
  },
  {
    _id: '64d49a6d6536db755e372e08',
    serialId: 46,
    name: 'Light Blue Ballgown',
    description: 'New Outfit LA N6',
    category: 'Speak Now',
    pointValue: 6,
    image: 'https://pbs.twimg.com/media/F3JSZloWwAYJhzR?format=jpg&name=large',
  },
  {
    _id: '64d49c336536db755e372e09',
    serialId: 47,
    name: 'Blue Dress',
    description: 'New Outfit LA N6',
    category: 'Folklore',
    pointValue: 5,
    image: 'https://pbs.twimg.com/media/F3JW0esWoAAXwqw?format=jpg&name=large',
  },
  {
    _id: '64d5a1c1799ae1c0c7ade7d0',
    serialId: 48,
    name: 'Blue Surprise',
    description: 'New Outfit LA N6',
    designer: 'Jessica Jones',
    category: 'Surprise Songs',
    pointValue: 4,
    image:
      'https://people.com/thmb/041JgeDXpmzUmqhjKzOOnFh_tvw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(999x0:1001x2)/taylor-swift-eras-tour-1989-081023-1-dd06aeed14e6435b972776ee1f0efec5.jpg',
  },
  {
    _id: '64d5a272799ae1c0c7ade7d1',
    serialId: 49,
    name: 'Blue 2 Piece',
    description: 'New Outfit LA N6',
    designer: 'Roberto Cavalli',
    category: '1989',
    pointValue: 4,
    image: 'https://opoyi.com/wp-content/uploads/2023/05/FxGDuaPWAAAZHye-e1685151387750.jpeg',
  },
  {
    _id: '655196b715a1dc327f7f93a6',
    serialId: 50,
    name: 'Hot Pink Bodysuit',
    description: 'New Outfit Buenos Aires N1',
    category: 'Lover',
    designer: 'Versace',
    pointValue: 4,
    image: 'https://pbs.twimg.com/media/F-iFfwgWgAAv67f?format=jpg',
  },
  {
    _id: { $oid: '6551983d15a1dc327f7f93a8' },
    serialId: { $numberInt: '51' },
    name: 'Pink The Man Jacket',
    description: 'New Outfit Buenos Aires N1',
    category: 'Lover',
    designer: 'Versace',
    pointValue: { $numberInt: '4' },
    image: 'https://pbs.twimg.com/media/F-iRO3XWQAECIaL?format=jpg',
  },
];
